### ISSUE TITLE
Contribution to Hugging Face 🤗 cookbook: Utilize advanced retrieval techniques with Hugging Face LLMs for RAG

### ISSUE THREAD

**Issue by moaaz12-web** [huggingface/cookbook#31]
I would like to contribute to the Hugging Face 🤗 repository by adding a notebook on utilizing different retrieval techniques like BM25 retriever, multi-vector retriever, multi-query retriever, ensemble retriever, and merger retriever on document question answering with Hugging Face 🤗 models as the llms and embedding models.

I've extensively explored langchain's features and would love to contribute to the open source community and share my knowledge.

**Comment by moaaz12-web** [comment]
[@MKhalusova](https://github.com/MKhalusova) would love to know how to proceed with the next steps. Should I fork the repo and open a new pull request?

**Comment by MKhalusova** [comment]
This sounds like a great addition to the cookbook! Go ahead, fork the repo, and create a pull request. 
Check out other merged notebooks to get an idea for the format, make sure to add your notebook to the `_toctree.yml`, and to the list of latest notebooks in `index.md`.

When done, add me as a reviewer.
