### ISSUE TITLE
Step 5 and Step 6 are out of order in **rag_with_hugging_face_gemma_mongodb.ipynb**

### ISSUE THREAD

**Issue by rasyosef** [huggingface/cookbook#54]
In the **rag_with_hugging_face_gemma_mongodb.ipynb** notebook, **Step 5** is to create a vector search index in the `movie_collection_2` MongoDB collection, but this collection has not been created yet in the notebook and it is later created in **Step 6**. Therefore, I think these two steps are out of order and should be switched.

The notebook is also missing the instructions to create an atlas vector search index in **Step 5**. It says "Follow instructions here:" but then the next paragraph does not contain instructions.

https://github.com/huggingface/cookbook/blob/main/notebooks/en/rag_with_hugging_face_gemma_mongodb.ipynb

**Comment by MKhalusova** [comment]
cc @RichmondAlake Can you take a look please?

**Comment by RichmondAlake** [comment]
@rasyosef 

Thanks for bringing this to my attention.

I am working on a PR to fill in the information gap.

Please do reach out if you encounter any further gaps and I'll address them promptly

**Comment by rasyosef** [comment]
@RichmondAlake 
Great! 

I had one more suggestion. It might be worth including a link to the Gemma model repo on HuggingFace (https://huggingface.co/google/gemma-2b-it) in the notebook.

Since Gemma is a **Gated model**, people who are using it for the first time would need to accept google's terms and conditions before they are granted access to the model, and it would also require them to `notebook_login` using their HuggingFace access token in order to download the model on google colab.
