### ISSUE TITLE
Contribution to Hugging Face 🤗 cookbook: Add two tutorials on Setfit and using HF Inference Endpoints

### ISSUE THREAD

**Issue by sdiazlor** [huggingface/cookbook#55]
From [Argilla](https://github.com/argilla-io), we would like to contribute with two new tutorials.

* Fine-tune a SetFit model using the ArgillaTrainer: to learn how to use the `ArgillaTrainer` to fine-tune a SetFit model on a `FeedbackDataset` made of categorical questions like `LabelQuestion` and `MultiLabelQuestion`.
* Create a legal preference dataset: to learn how to use the Notus model on Inference Endpoints to create a legal preference dataset based on RAG instructions from the European AI Act

**Comment by MKhalusova** [comment]
Hi @sdiazlor ! Both suggestions sound good to me, I look forward to reviewing your notebooks! For the first one, please add some context on use cases, and reasoning for the choices made.
