### ISSUE TITLE
PII detection for secure use of LLM api's

### ISSUE THREAD

**Issue by asusevski** [huggingface/cookbook#96]
I'd love to contribute a PII detection notebook with applications in Finance. Since finance is highly regulated, one of the principal concerns with using any ML endpoints including LLMs is proprietary data being leaked. Some orgs (mine included) use a gateway that filters out PII before hitting the desired endpoint. Wealthsimple has shared a repo on this (https://github.com/wealthsimple/llm-gateway) and if I may contribute, I'll likely make use of their scripts as a starting point and create a walk through covering what using the gateway might look like in an industry setting.

I know that this may not be 100% in the domain of "open-source AI" but given that the biggest barrier most companies face with adopting LLM APIs (at this point, the easiest way for orgs to adopt AI) is the concerns around data privacy, this may encourage adoption faster which can then be a stepping stone towards further ML adoption within the org.

@merveenoyan @stevhliu thoughts?

**Comment by stevhliu** [comment]
This sounds like a very cool use case! However, the Cookbook's purpose is to showcase open tools that are freely accessible to everyone. Would it be possible for your notebook to use Cohere's free Trial API key? It looks like llm-gateway's other supported options, OpenAI and AWS Bedrock, require payment.

**Comment by asusevski** [comment]
Absolutely! we can do that. Alternatively I could also use llama cpp server to spoof an endpoint and re-implement the sanitizers in that repo, if that would improve accessibility.

**Comment by stevhliu** [comment]
Cool, let's stick with using Cohere's free Trial API key for now just to keep things more straightforward :)
